language: node_js
node_js:
- '0.10'
after_success: -"curl --ftp-create-dirs -T '{./dist/index.html,./dist/geoapp.js}'
  -u $FTP_USER:$FTP_PASSWORD ftp://raffalli-marc-ed.com/"
env:
  global:
  - secure: ZjzJQI8KmNMTC+sFt2p2A2n2TkqY9iPOm4g83TmjJFahQh8ZaTTqalnBetXuZN1xRf7WPtN8zO3SdZ6uLh+EsMjo9JvK8OHeKohBlZE12PR7iISgmUY1bj9ti2KnfI6j1TzsrUI+oaUn4lpON5fmfKVO8VkU2uE2Vkl3jeytZ8M=
  - secure: ca4+mvDyRax0/ezxPjUu7mZsfkYFbxQaFqvj6i5ydys5hL68yaw+evVvNlbMKwCnR23h4G88arsyk3BPWHrNvAzgW4NANpPe79v2hnJHudwhXO9KoP8f9VL1gH8mTmMfdzbC+AdcYQr8g+BJrMuZ2YGaZ0aSXLCWN3ZYnEsRcBc=
